GET http://localhost:3000/petcustomers

###

GET http://localhost:3000/petcustomers/5f541a276cc2af3358f2e0f1

###
POST  http://localhost:3000/localhost:3000/

###
DELETE http://localhost:3000/localhost:3000/petcustomers/"5f5e2df840548602bcae4192"
