GET http://localhost:3000/petcustomers

###

GET http://localhost:3000/petcustomers/5f541

###
POST  http://localhost:3000/localhost:3000/

###
DELETE http://localhost:3000/petcustomers/5f5029b380909c548864edf8
